apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyterhub
subjects:
- kind: ServiceAccount
  name: jupyterhub-hub
  namespace: $(jupyterhub_namespace)
