apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  name: cuda-11-0-3-build
  labels:
    cuda-version: "$(cuda_version)"
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.7
          volumeMounts:
            - name: cuda-ubi8-build-chain
              mountPath: /tmp/

          # work around unwriteable HOME dir / for unprivileged pods causing OC commands to be slow in pods
          env:
            - name: HOME
              value: /tmp
            - name: BUILD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath:
                    metadata.namespace

          command:
            - /bin/bash
            - -c
            - |
              set -x
              echo "PWD: $PWD"
              oc create -n ${BUILD_NAMESPACE} -f /tmp/gpu-notebook.yaml
              oc create -n ${BUILD_NAMESPACE} -f /tmp/cuda-ubi8-build-chain.yaml
          imagePullPolicy: IfNotPresent
          name: cuda-11-0-3-build
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cuda-11.0.3-build-job
      serviceAccountName: cuda-11.0.3-build-job
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cuda-ubi8-build-chain
          configMap:
            name: cuda-build-chain
            items:
              - key: gpu-notebook.yaml
                path: gpu-notebook.yaml
              - key: cuda-ubi8-build-chain.yaml
                path: cuda-ubi8-build-chain.yaml
