apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: cuda-11.0.3-build-job
  name: cuda-11.0.3-build-job
rules:
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - create
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - events
      - persistentvolumeclaims
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - build.openshift.io
    resources:
      - builds
      - buildconfigs
    verbs:
      - create
      - patch
      - update
      - get
      - list
      - watch
