apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - cuda-build.serviceaccount.yaml
  - cuda-build-role.yaml
  - cuda-build-rolebinding.yaml
  - cuda-buildchain.configmap.yaml
  - cuda-build-job.yaml
configMapGenerator:
  - env: params.env
    name: parameters
generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: cuda_version
    objref:
      kind: ConfigMap
      name: parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.cuda_version
configurations:
  - params.yaml
