kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-proxy
subjects:
- kind: ServiceAccount
  name: traefik-proxy
